### ISSUE TITLE
How to validate a token in each request?

### ISSUE THREAD

**Issue by python-programmer** [imbolc/aiohttp-login#10]
Hi, thank you for your great work.

When an user redirect to google login page and successfully logged in and back to the site, she/he want to access to some resource on the server.

She/he add the token in authorization header in each request and she/he expects to get related resource (based on her permission)

**Question** is : How to validate a token in each request(token decoding and validation - google client)?

Thanks

**Comment by imbolc** [comment]
Hi :) Sorry for silence, this lib is relying on aiohttp_session, you can dig into it to understand if it has (or allows to write) backend you needed
