### ISSUE TITLE
[Question] Unable to run tests and example

### ISSUE THREAD

**Issue by gyermolenko** [imbolc/aiohttp-login#14]
Hi.

Could you please provide some details about database setup for running tests?
I get errors about invalid user or password even if I run one empty test with only the `client` fixture.

I've tried to run `pytest` with local `postgres` and with docker.
Also tried to update places where [DATABASE](https://github.com/imbolc/aiohttp-login/blob/master/tests/utils.py#L22) placeholder is used in `utils.py` with my connection details.

**Comment by imbolc** [comment]
You can make yourself postgres admin with `sudo su postgres -c "cd /; createuser -s user"`
Or change this line so it would work with your db setup: https://github.com/imbolc/aiohttp-login/blob/master/tests/utils.py#L43

**Comment by gyermolenko** [comment]
Sorry I didn't respond earlier.
Thanks, I will try to setup tests/example in the nearest days and leave follow-up comments here probably..

**Comment by gyermolenko** [comment]
Had to update a few things since I wasn't  comfortable with running everything from superuser with empty password.
For future explorers: 
- I had to create `citext` extension as superuser
- grant few privileges for `aiohttp_login` db user
- update [dsn](https://github.com/imbolc/aiohttp-login/blob/master/tests/utils.py#L43)
- update [os.system connection string](https://github.com/imbolc/aiohttp-login/blob/master/tests/utils.py#L94)
- comment-out `pytest_generate_tests` to not try to run tests with mongo storage.

I will close the issue now.
