### ISSUE TITLE
[Question] Is it required to have database schema like in "pg_tables.sql" to use the lib?

### ISSUE THREAD

**Issue by gyermolenko** [imbolc/aiohttp-login#15]
Is it possible to add this lib to existing application and not modify existing tables?
Is it required to run "pg_tables.sql" after pip install?

**Comment by imbolc** [comment]
You can write your own storage to work with existing db structure, look at [asyncpg_storage](https://github.com/imbolc/aiohttp-login/blob/master/aiohttp_login/asyncpg_storage.py) for methods it should provide. 

> Is it required to run "pg_tables.sql" after pip install?

Only if you're using builtin asyncpg_storage.
