### ISSUE TITLE
requirements.txt does not specify versions

### ISSUE THREAD

**Issue by FlorianLudwig** [imbolc/aiohttp-login#16]
The requirements.txt should specify compatible versions.  For example the current code is for motor 1 and not compatible with motor 2.

With the current setup motor 2 is installed but not working.

**Comment by imbolc** [comment]
Thanks, @FlorianLudwig , would you also make tests passing?

![selection-imbolc-003](https://user-images.githubusercontent.com/747996/51438048-836dc180-1cd9-11e9-94b0-3f1d7a1e6b4a.png)

**Comment by imbolc** [comment]
Archiving the project
