### ISSUE TITLE
Possible vulnerability in @admin_required decorator

### ISSUE THREAD

**Issue by femtocat** [imbolc/aiohttp-login#18]
I am probably reading the code wrong, and project is probably already abandoned, but to me it looks like @admin_required decorator works in this fashion:

1. Checks if user is logged in
2. Executes the handler
3. And only then checks if user is actually an admin. If he is not, an exception is raised.

As far as i can tell, that means that you can't rely on @admin_required to, say, protect administrative API endpoints, since handler will be executed anyway. Attacker will get his 403, sure, but changes to the system state will already been made at this point.

**Comment by imbolc** [comment]
Hi :) Yes, you're right in everything. I don't plan to maintain the project and should probably archive it. So you'll still would probably use your fork of it. But feel free to make a PR if for some reason you want to :)

**Comment by imbolc** [comment]
Archiving the project
